name: VoteBan
version: '${project.version}'
main: de.urbance.voteban.Main
api-version: 1.19
commands:
  voteban:
    description: voteban a player
    aliases: vb
  vba:
    description: voteban administration commands